'use client'

import React, { useState } from 'react'
import { useLang } from '../../lib/LangContext'
import { useTheme } from '../../lib/ThemeContext'
import Link from 'next/link'

export default function TermsPage() {
  const { isRTL, t, setLang } = useLang()
  const { theme } = useTheme()
  const [lang, setLangState] = useState(isRTL ? 'ar' : 'en')

  const toggleLang = () => {
    const newLang = lang === 'ar' ? 'en' : 'ar'
    setLangState(newLang)
    setLang(newLang)
  }

  const content = {
    en: {
      title: 'Terms of Service',
      subtitle: 'By using Naz Autoreply you agree to these terms',
      sections: [
        {
          title: '1. Acceptance of Terms',
          content: `By creating an account and using Naz Autoreply you agree to be bound by these terms. If you do not agree, do not use the platform. These terms constitute a legally binding agreement between you and Naz Autoreply.`
        },
        {
          title: '2. Description of Service',
          content: `Naz Autoreply provides an AI-powered automated messaging platform that connects to your social media and email channels and responds to your customers automatically on your behalf using artificial intelligence. The platform is intended for business use by e-commerce merchants, entrepreneurs, and business owners.`
        },
        {
          title: '3. Account Registration',
          items: [
            'You must provide accurate and complete information when creating your account',
            'You are responsible for maintaining the security of your account credentials',
            'You must be at least 18 years old to use the platform',
            'One person or business entity may not maintain more than one free account',
            'You are responsible for all activity that occurs under your account'
          ]
        },
        {
          title: '4. Acceptable Use',
          items: [
            'Use the platform to send spam, unsolicited messages, or bulk promotional messages in violation of WhatsApp, Meta, or Google policies',
            'Use the platform for any illegal activity or to violate any applicable laws',
            'Use the platform to harass, abuse, or harm any individual',
            'Attempt to reverse engineer, hack, or disrupt the platform',
            'Resell or sublicense access to the platform without written permission',
            'Use the AI to generate misleading, false, or harmful content',
            'Violate Meta\'s, Google\'s, or WhatsApp\'s terms of service through your use of connected channels'
          ],
          intro: 'By using Naz Autoreply you agree NOT to:'
        },
        {
          title: '5. AI-Generated Content',
          items: [
            'The automated replies generated by Naz Autoreply are produced by artificial intelligence',
            'You are fully responsible for all messages sent through your connected channels, including AI-generated replies',
            'You should review your AI reply settings and business profile regularly to ensure responses are accurate',
            'Naz Autoreply is not liable for any AI-generated response that causes misunderstanding, loss, or damage',
            'You must comply with any local laws requiring disclosure that a message was generated by AI'
          ]
        },
        {
          title: '6. Channel Connections & Third Party Platforms',
          items: [
            'Connecting your Facebook, Instagram, Gmail, or WhatsApp accounts is done voluntarily',
            'You grant Naz Autoreply permission to send and receive messages on your behalf through connected channels',
            'Your continued access depends on the policies of Meta, Google, and WhatsApp — we cannot guarantee access if those platforms change their policies',
            'You may disconnect any channel at any time from your dashboard'
          ]
        },
        {
          title: '7. Subscription & Billing',
          items: [
            'Naz Autoreply offers Free, Starter, and Pro subscription plans',
            'Paid subscriptions are billed monthly in advance',
            'All payments are processed securely by Stripe',
            'Subscriptions automatically renew unless cancelled before the renewal date',
            'Refunds are not provided for partial months',
            'We reserve the right to change pricing with 30 days notice to existing subscribers',
            'Failure to pay will result in downgrade to the Free plan'
          ]
        },
        {
          title: '8. Intellectual Property',
          items: [
            'Naz Autoreply and all its components, designs, code, and content are owned by Naz Autoreply and protected by intellectual property laws',
            'You retain ownership of your business data, messages, and content',
            'You grant Naz Autoreply a limited license to process your data solely for the purpose of providing the service'
          ]
        },
        {
          title: '9. Limitation of Liability',
          items: [
            'Naz Autoreply is provided "as is" without warranties of any kind',
            'We do not guarantee 100% uptime or uninterrupted service',
            'We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform',
            'Our total liability to you shall not exceed the amount you paid in the last 3 months'
          ]
        },
        {
          title: '10. Termination',
          items: [
            'You may cancel your account at any time from dashboard settings',
            'We reserve the right to suspend or terminate accounts that violate these terms without notice',
            'Upon termination, your data will be retained for 30 days then permanently deleted',
            'You may request immediate deletion by emailing support@nazautoreply.com'
          ]
        },
        {
          title: '11. Governing Law',
          content: `These terms are governed by the laws of the Kingdom of Saudi Arabia. Any disputes shall be resolved in the competent courts of Saudi Arabia.`
        },
        {
          title: '12. Changes to Terms',
          content: `We may update these terms at any time. We will notify users by email 14 days before significant changes take effect. Continued use after changes constitutes acceptance of the new terms.`
        },
        {
          title: '13. Contact',
          content: `For any questions about these terms: legal@nazautoreply.com — or write to us at Naz Autoreply, Kingdom of Saudi Arabia.`
        }
      ],
      lastUpdated: 'Last updated: July 2026',
      backHome: '← Back to Homepage',
      privacyPolicy: 'Privacy Policy'
    },
    ar: {
      title: 'شروط الخدمة',
      subtitle: 'باستخدام ناز أوتو ريبلي فإنك توافق على هذه الشروط',
      sections: [
        {
          title: '1. قبول الشروط',
          content: `بإنشاء حساب واستخدام ناز أوتو ريبلي فإنك توافق على الالتزام بهذه الشروط. إذا كنت لا توافق، لا تستخدم المنصة. تشكل هذه الشروط اتفاقية ملزمة قانونياً بينك وبين ناز أوتو ريبلي.`
        },
        {
          title: '2. وصف الخدمة',
          content: `توفر ناز أوتو ريبلي منصة مراسلة آلية مدعومة بالذكاء الاصطناعي تتصل بقنوات التواصل الاجتماعي والبريد الإلكتروني الخاصة بك وترد على عملائك تلقائياً نيابة عنك باستخدام الذكاء الاصطناعي. المنصة مخصصة للاستخدام التجاري من قبل تجار التجارة الإلكترونية ورواد الأعمال وأصحاب الأعمال.`
        },
        {
          title: '3. تسجيل الحساب',
          items: [
            'يجب عليك تقديم معلومات دقيقة وكاملة عند إنشاء حسابك',
            'أنت مسؤول عن الحفاظ على أمان بيانات اعتماد حسابك',
            'يجب أن تكون عمره 18 عاماً على الأقل لاستخدام المنصة',
            'لا يجوز لشخص واحد أو كيان تجاري الحفاظ على أكثر من حساب مجاني واحد',
            'أنت مسؤول عن جميع الأنشطة التي تحدث تحت حسابك'
          ]
        },
        {
          title: '4. الاستخدام المقبول',
          intro: 'باستخدام ناز أوتو ريبلي فإنك توافق على عدم:',
          items: [
            'استخدام المنصة لإرسال الرسائل غير المرغوب فيها أو الرسائل الترويجية الجماعية انتهاكاً لسياسات واتساب أو ميتا أو جوجل',
            'استخدام المنصة لأي نشاط غير قانوني أو انتهاك أي قوانين معمول بها',
            'استخدام المنصة لمضايقة أو إيذاء أو إلحاق الضرر بأي فرد',
            'المحاولة لهندسة عكسية أو اختراق أو تعطيل المنصة',
            'إعادة بيع أو ترخيص الوصول إلى المنصة دون إذن كتابي',
            'استخدام الذكاء الاصطناعي لتوليد محتوى مضلل أو كاذب أو ضار',
            'انتهاك شروط خدمة ميتا أو جوجل أو واتساب من خلال استخدامك للقنوات المتصلة'
          ]
        },
        {
          title: '5. المحتوى المولد بالذكاء الاصطناعي',
          items: [
            'الردود الآلية التي تولدها ناز أوتو ريبلي تنتجها الذكاء الاصطناعي',
            'أنت مسؤول بالكامل عن جميع الرسائل المرسلة عبر قنواتك المتصلة، بما في ذلك الردود المولدة بالذكاء الاصطناعي',
            'يجب عليك مراجعة إعدادات الرد بالذكاء الاصطناعي والملف التجاري الخاص بك بانتظام لضمان دقة الردود',
            'ناز أوتو ريبلي غير مسؤولة عن أي رد مولد بالذكاء الاصطناعي يسبب سوء فهم أو خسارة أو ضرر',
            'يجب عليك الامتثال لأي قوانين محلية تتطلب الإفصاح بأن الرسالة تم توليدها بالذكاء الاصطناعي'
          ]
        },
        {
          title: '6. اتصالات القنوات ومنصات الطرف الثالث',
          items: [
            'ربط حسابات فيسبوك أو إنستغرام أو جيميل أو واتساب يتم طوعياً',
            'تمنح ناز أوتو ريبلي إذناً لإرسال واستقبال الرسائل نيابة عنك عبر القنوات المتصلة',
            'استمرار وصولك يعتمد على سياسات ميتا وجوجل وواتساب — لا يمكننا ضمان الوصول إذا قامت تلك المنصات بتغيير سياساتها',
            'يمكنك فصل أي قناة في أي وقت من لوحة التحكم'
          ]
        },
        {
          title: '7. الاشتراك والفوترة',
          items: [
            'تقدم ناز أوتو ريبلي خطط اشتراك مجانية ومبتدئة واحترافية',
            'يتم فوترة الاشتراكات المدفوعة شهرياً مقدماً',
            'تتم معالجة جميع المدفوعات بشكل آمن بواسطة Stripe',
            'تجدد الاشتراكات تلقائياً ما لم يتم إلغاؤها قبل تاريخ التجديد',
            'لا يتم تقديم المبالغ المستردة للأشهر الجزئية',
            'نحتفظ بالحق في تغيير التسعير مع إشعار 30 يوماً للمشتركين الحاليين',
            'عدم الدفع سيؤدي إلى تخفيض إلى الخطة المجانية'
          ]
        },
        {
          title: '8. الملكية الفكرية',
          items: [
            'ناز أوتو ريبلي وجميع مكوناتها وتصاميمها ورموزها ومحتواها مملوكة لناز أوتو ريبلي ومحمية بموجب قوانين الملكية الفكرية',
            'أنت تحتفظ بملكية بيانات عملك ورسائلك ومحتواك',
            'تمنح ناز أوتو ريبلي ترخيصاً محدوداً لمعالجة بياناتك فقط لغرض تقديم الخدمة'
          ]
        },
        {
          title: '9. تحديد المسؤولية',
          items: [
            'ناز أوتو ريبلي تقدم "كما هي" دون أي ضمانات من أي نوع',
            'نحن لا نضمن وقت تشغيل 100% أو خدمة غير متقطعة',
            'نحن غير مسؤولين عن أي أضرار غير مباشرة أو عرضية أو تبعية تنشأ عن استخدامك للمنصة',
            'لا تتجاوز مسؤوليتنا الإجمالية تجاهك المبلغ الذي دفعته في آخر 3 أشهر'
          ]
        },
        {
          title: '10. الإنهاء',
          items: [
            'يمكنك إلغاء حسابك في أي وقت من إعدادات لوحة التحكم',
            'نحتفظ بالحق في تعليق أو إنهاء الحسابات التي تنتهك هذه الشروط دون إشعار',
            'عند الإنهاء، سيتم الاحتفاظ ببياناتك لمدة 30 يوماً ثم حذفها نهائياً',
            'يمكنك طلب الحذف الفوري عن طريق البريد الإلكتروني support@nazautoreply.com'
          ]
        },
        {
          title: '11. القانون الحاكم',
          content: `تحكم هذه الشروط قوانين المملكة العربية السعودية. يتم حل أي نزاعات في المحاكم المختصة في المملكة العربية السعودية.`
        },
        {
          title: '12. التغييرات على الشروط',
          content: `قد نقوم بتحديث هذه الشروط في أي وقت. سنقوم بإخطار المستخدمين بالبريد الإلكتروني قبل 14 يوماً من دخول التغييرات الهامة حيز التنفيذ. الاستمرار في الاستخدام بعد التغييرات يشكل قبولاً للشروط الجديدة.`
        },
        {
          title: '13. اتصل بنا',
          content: `لأي أسئلة حول هذه الشروط: legal@nazautoreply.com — أو اكتب إلينا على ناز أوتو ريبلي، المملكة العربية السعودية.`
        }
      ],
      lastUpdated: 'آخر تحديث: يوليو 2026',
      backHome: '→ العودة إلى الصفحة الرئيسية',
      privacyPolicy: 'سياسة الخصوصية'
    }
  }

  const c = content[lang as keyof typeof content]

  return (
    <div className="min-h-screen" style={{ background: 'var(--background)' }}>
      {/* Header */}
      <header className="border-b" style={{ borderColor: 'var(--border)' }}>
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <span style={{ color: 'var(--primary)', fontSize: 24, filter: 'drop-shadow(0 0 8px rgba(108,99,255,0.8))' }}>✦</span>
            <span className="text-xl font-black" style={{ color: 'var(--text-primary)', letterSpacing: '-0.04em' }}>Naz</span>
          </Link>
          <button
            onClick={toggleLang}
            className="px-4 py-2 rounded-lg text-sm font-bold transition-all"
            style={{ 
              background: 'rgba(255,255,255,0.04)', 
              border: '1px solid var(--border)', 
              color: 'var(--text-secondary)' 
            }}
          >
            {lang === 'ar' ? '🇬🇧 English' : '🇸🇦 العربية'}
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <div className="mb-12">
          <h1 className="text-4xl font-black mb-4" style={{ color: 'var(--text-primary)' }}>
            {c.title}
          </h1>
          <p className="text-lg" style={{ color: 'var(--text-secondary)' }}>
            {c.subtitle}
          </p>
        </div>

        <div className="space-y-10">
          {c.sections.map((section, index) => (
            <section key={index}>
              <h2 className="text-xl font-bold mb-4" style={{ color: 'var(--text-primary)' }}>
                {section.title}
              </h2>
              {section.intro && (
                <p className="mb-4 leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                  {section.intro}
                </p>
              )}
              {section.content ? (
                <p className="leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                  {section.content}
                </p>
              ) : (
                <ul className="space-y-3" style={{ color: 'var(--text-secondary)' }}>
                  {section.items?.map((item, itemIndex) => (
                    <li key={itemIndex} className="flex items-start gap-3">
                      <span style={{ color: 'var(--primary)', marginTop: '2px' }}>•</span>
                      <span className="leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>

        <div className="mt-16 pt-8 border-t" style={{ borderColor: 'var(--border)' }}>
          <p className="text-sm mb-4" style={{ color: 'var(--text-secondary)' }}>
            {c.lastUpdated}
          </p>
          <div className="flex items-center gap-6">
            <Link 
              href="/"
              className="inline-flex items-center gap-2 text-sm font-bold transition-colors"
              style={{ color: 'var(--primary)' }}
            >
              {c.backHome}
            </Link>
            <Link 
              href="/privacy"
              className="text-sm font-bold transition-colors"
              style={{ color: 'var(--text-secondary)' }}
            >
              {c.privacyPolicy}
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}
