'use client'

import React, { useState } from 'react'
import { useLang } from '../../lib/LangContext'
import Link from 'next/link'
import { Scale, ShieldCheck, AlertCircle, FileText, ArrowLeft, ArrowRight, Sparkles, Globe } from 'lucide-react'

export default function TermsPage() {
  const { isRTL, setLang } = useLang()
  const [lang, setLangState] = useState<'ar' | 'en'>(isRTL ? 'ar' : 'en')

  const toggleLang = () => {
    const newLang = lang === 'ar' ? 'en' : 'ar'
    setLangState(newLang)
    setLang(newLang)
  }

  const content = {
    en: {
      title: 'Terms of Service',
      badge: 'Legal Agreement & Operational Rules',
      subtitle: 'Please review the terms and conditions governing the use of Naz Biz (Naz Autoreply) AI communication tools, platform integrations, and subscription services.',
      lastUpdated: 'Last updated: August 2026',
      backHome: 'Back to Platform',
      privacyPolicy: 'Privacy Policy',
      contactUs: 'Questions regarding legal terms? Email legal@nazbiz.io',
      sections: [
        {
          id: 'acceptance',
          icon: <Scale className="w-5 h-5 text-indigo-400" />,
          title: '1. Acceptance of Terms',
          content: `By registering an account, connecting channels, or using Naz Biz ("Naz Autoreply", "we", "our", "the platform"), you enter into a legally binding agreement to comply with these terms. If you do not agree to these conditions, you must not access or use our services.`
        },
        {
          id: 'service-desc',
          icon: <Sparkles className="w-5 h-5 text-purple-400" />,
          title: '2. Description of Platform Services',
          content: `Naz Biz provides an enterprise multi-channel AI customer support platform. The service aggregates customer conversations across messaging channels (Meta Pages, Instagram, WhatsApp, Telegram, Gmail, Salla, Shopify, TikTok) and generates automated contextual replies using artificial intelligence.`
        },
        {
          id: 'acceptable-use',
          icon: <AlertCircle className="w-5 h-5 text-pink-400" />,
          title: '3. Acceptable Use & Prohibited Conduct',
          intro: 'When using Naz Biz, you agree strictly NOT to:',
          items: [
            'Send unsolicited commercial bulk spam or engage in mass messaging that violates WhatsApp, Meta, or Google policies.',
            'Use the platform for fraudulent, illegal, defamatory, or harmful activities.',
            'Attempt to reverse engineer, disrupt, or bypass platform security controls.',
            'Resell, license, or redistribute platform access without prior written consent.',
            'Violate the terms of service of any connected channel (Meta, Google, WhatsApp, Telegram, Salla, Shopify).'
          ]
        },
        {
          id: 'ai-responsibility',
          icon: <FileText className="w-5 h-5 text-blue-400" />,
          title: '4. AI-Generated Content & Merchant Oversight',
          items: [
            'Automated customer replies are generated by AI models using your business knowledge base.',
            'You maintain full responsibility and ownership for all automated messages sent through your connected accounts.',
            'You are expected to review business profiles, knowledge bases, and AI parameters regularly to ensure accuracy.',
            'Naz Biz is not liable for misunderstandings or damages arising from AI-generated responses.',
            'Merchants must comply with local laws regarding disclosures for AI-assisted customer communication.'
          ]
        },
        {
          id: 'channels',
          icon: <Globe className="w-5 h-5 text-emerald-400" />,
          title: '5. Channel Connections & Third-Party Platforms',
          items: [
            'Channel connections (WhatsApp, Meta, Gmail, Telegram, Salla, Shopify) are configured voluntarily by the merchant.',
            'You grant Naz Biz authorization to ingest customer messages and dispatch automated responses on your behalf.',
            'Platform uptime and channel availability depend on third-party provider APIs (Meta, Google, WhatsApp, Telegram).',
            'You may disconnect any channel at any time directly from your dashboard settings.'
          ]
        },
        {
          id: 'billing',
          icon: <ShieldCheck className="w-5 h-5 text-amber-400" />,
          title: '6. Subscriptions, Payments & Cancellations',
          items: [
            'Subscriptions (Free, Starter, Pro, Enterprise) are billed on a recurring monthly or annual basis.',
            'All billing transactions are processed via secure PCI-compliant gateways (Paymob & Stripe).',
            'Subscriptions renew automatically unless cancelled before the renewal date via dashboard settings.',
            'Failed subscription renewals may result in automatic feature degradation or channel pause.'
          ]
        },
        {
          id: 'termination',
          icon: <Scale className="w-5 h-5 text-red-400" />,
          title: '7. Termination & Account Deletion',
          content: `You can terminate your subscription at any time. Naz Biz reserves the right to suspend or terminate accounts that violate platform policies or terms of service without prior notice.`
        }
      ]
    },
    ar: {
      title: 'شروط الخدمة',
      badge: 'الاتفاقية القانونية وقواعد التشغيل',
      subtitle: 'يرجى مراجعة الشروط والأحكام التي تحكم استخدام منصة ناز بيز (Naz Autoreply) وأدوات الذكاء الاصطناعي وتكاملات القنوات والاشتراكات.',
      lastUpdated: 'آخر تحديث: أغسطس 2026',
      backHome: 'العودة إلى المنصة',
      privacyPolicy: 'سياسة الخصوصية',
      contactUs: 'أسئلة حول الشروط القانونية؟ تواصل معنا عبر legal@nazbiz.io',
      sections: [
        {
          id: 'acceptance',
          icon: <Scale className="w-5 h-5 text-indigo-400" />,
          title: '1. قبول الشروط',
          content: `بإنشاء حساب أو ربط القنوات أو استخدام منصة ناز بيز ("Naz Autoreply"، "نحن"، "المنصة")، فإنك تدخل في اتفاقية ملزمة قانونياً للالتزام بهذه الشروط. إذا كنت لا توافق على هذه الأركان، فيجب عليك الامتناع عن استخدام المنصة.`
        },
        {
          id: 'service-desc',
          icon: <Sparkles className="w-5 h-5 text-purple-400" />,
          title: '2. وصف خدمات المنصة',
          content: `توفر ناز بيز منصة متكاملة لأتمتة خدمة العملاء بالذكاء الاصطناعي. تجمع المنصة المحادثات عبر قنوات المراسلة (فيسبوك، إنستغرام، واتساب، تليجرام، جيميل، سلة، شوبيفاي، تيك توك) وتولد ردوداً سياقية فورية باستخدام الذكاء الاصطناعي.`
        },
        {
          id: 'acceptable-use',
          icon: <AlertCircle className="w-5 h-5 text-pink-400" />,
          title: '3. الاستخدام المقبول والأنشطة المحظورة',
          intro: 'عند استخدام ناز بيز، تتعهد بشكل قاطع بعدم القيام بما يلي:',
          items: [
            'إرسال الرسائل غير المرغوب فيها (Spam) أو تنفيذ الحملات الجماعية المخالفة لسياسات واتساب أو ميتا أو جوجل.',
            'استخدام المنصة لأغراض احتيالية، غير قانونية، أو ضارة.',
            'محاولة التفكيك العكسي أو اختراق ضوابط أمان المنصة.',
            'إعادة بيع أو ترخيص الوصول إلى المنصة دون موافقة كتابية مسبقة.',
            'مخالفة شروط خدمة المنصات المتصلة (ميتا، جوجل، واتساب، تليجرام، سلة، شوبيفاي).'
          ]
        },
        {
          id: 'ai-responsibility',
          icon: <FileText className="w-5 h-5 text-blue-400" />,
          title: '4. الردود الآلية وتأطير مسؤولية المتاجر',
          items: [
            'تُولد الردود الآلية بواسطة الذكاء الاصطناعي بناءً على قاعدة معارف نشاطك التجاري.',
            'تتحمل المنشأة والتاجر المسؤولية الكاملة عن كافة الرسائل المرسلة عبر الحسابات المتصلة.',
            'يتوجب على التاجر مراجعة بيانات ومعارف المنشأة بانتظام لضمان دقة الردود.',
            'ناز بيز غير مسؤولة عن أي سوء فهم أو أضرار ناتجة عن الردود الآلية للذكاء الاصطناعي.',
            'يجب الالتزام بالأنظمة المحلية التي تتطلب الإفصاح عن المراسلات الآلية.'
          ]
        },
        {
          id: 'channels',
          icon: <Globe className="w-5 h-5 text-emerald-400" />,
          title: '5. اتصال القنوات والمنصات الخارجية',
          items: [
            'يتم ربط القنوات (واتساب، ميتا، جيميل، تليجرام، سلة، شوبيفاي) طوعياً من قبل المستخدم.',
            'تمنح ناز بيز تفويضاً لإداراة الرسائل وإرسال الردود الآلية نيابة عنك.',
            'استمرارية الخدمة تعتمد على استقرار واجهات المنصات الخارجية (ميتا، جوجل، واتساب).',
            'يمكنك فصل أي قناة في أي وقت مباشرة من إعدادات لوحة التحكم.'
          ]
        },
        {
          id: 'billing',
          icon: <ShieldCheck className="w-5 h-5 text-amber-400" />,
          title: '6. الاشتراكات والدفع والإلغاء',
          items: [
            'تتم فوترة الاشتراكات (المجانية، المبتدئة، الاحترافية) على أساس دوري شهري أو سنوي.',
            'تتم معالجة كافة المدفوعات عبر بوابات مشفرة متوافقة مع معايير PCI (Paymob & Stripe).',
            'تتجدد الاشتراكات تلقائياً ما لم يتم إلغاؤها قبل تاريخ التجديد من لوحة التحكم.',
            'قد يؤدي تعثر الفوترة إلى إيقاف مؤقت لأتمتة القنوات.'
          ]
        },
        {
          id: 'termination',
          icon: <Scale className="w-5 h-5 text-red-400" />,
          title: '7. الإنهاء وحظر الحسابات',
          content: `يحق لك إلغاء حسابك في أي وقت. تحافظ ناز بيز على حقها في إيقاف أو إنهاء الحسابات المخالفة للشروط وقواعد الاستخدام دون إشعار مسبق.`
        }
      ]
    }
  }

  const c = content[lang]

  return (
    <div className={`min-h-screen font-sans ${lang === 'ar' ? 'rtl' : 'ltr'}`} style={{ background: '#090d16', color: '#f8fafc' }}>
      {/* Top Navbar */}
      <nav className="sticky top-0 z-50 backdrop-blur-xl border-b border-white/10 bg-slate-950/80">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-indigo-600 via-purple-600 to-pink-500 flex items-center justify-center shadow-lg shadow-indigo-500/20">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-black tracking-tight text-white">
              Naz <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400">Biz</span>
            </span>
          </Link>

          <div className="flex items-center gap-4">
            <button
              onClick={toggleLang}
              className="px-3.5 py-1.5 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 text-xs font-bold transition-all text-slate-200 flex items-center gap-2"
            >
              <Globe className="w-3.5 h-3.5" />
              {lang === 'ar' ? 'English' : 'العربية'}
            </button>
            <Link
              href="/privacy"
              className="hidden sm:flex items-center gap-2 px-4 py-1.5 rounded-xl text-xs font-bold text-indigo-300 hover:text-white border border-indigo-500/20 bg-indigo-500/10 transition-all"
            >
              {c.privacyPolicy}
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Header */}
      <section className="relative py-16 px-6 border-b border-white/5 bg-gradient-to-b from-indigo-950/30 via-slate-950 to-slate-950 text-center">
        <div className="max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-purple-500/30 bg-purple-500/10 text-purple-300 text-xs font-semibold mb-6">
            <Scale className="w-4 h-4 text-purple-400" />
            {c.badge}
          </div>
          <h1 className="text-3xl sm:text-5xl font-black tracking-tight mb-4 text-white">
            {c.title}
          </h1>
          <p className="text-sm sm:text-base text-slate-400 leading-relaxed mb-4 max-w-2xl mx-auto">
            {c.subtitle}
          </p>
          <div className="text-xs font-medium text-slate-500">
            {c.lastUpdated}
          </div>
        </div>
      </section>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-16">
        <div className="space-y-8">
          {c.sections.map((sec, idx) => (
            <div
              key={sec.id || idx}
              className="p-6 sm:p-8 rounded-2xl border border-white/10 bg-slate-900/40 backdrop-blur-sm hover:border-purple-500/30 transition-all shadow-xl shadow-black/20"
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2.5 rounded-xl bg-white/5 border border-white/10">
                  {sec.icon}
                </div>
                <h2 className="text-lg sm:text-xl font-bold text-white tracking-tight">
                  {sec.title}
                </h2>
              </div>

              {sec.content && (
                <p className="text-sm sm:text-base text-slate-300 leading-relaxed font-normal">
                  {sec.content}
                </p>
              )}

              {sec.intro && (
                <p className="text-sm sm:text-base text-slate-300 leading-relaxed mb-4">
                  {sec.intro}
                </p>
              )}

              {sec.items && (
                <ul className="space-y-3 mt-3">
                  {sec.items.map((item, itemIdx) => (
                    <li key={itemIdx} className="flex items-start gap-3 text-sm sm:text-base text-slate-300">
                      <span className="mt-2 w-1.5 h-1.5 rounded-full bg-purple-400 shrink-0" />
                      <span className="leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </div>

        {/* Footer Contact */}
        <div className="mt-12 text-center p-6 sm:p-8 rounded-2xl border border-white/10 bg-gradient-to-r from-purple-950/20 via-indigo-950/20 to-slate-900/50">
          <p className="text-sm font-medium text-slate-300">
            {c.contactUs}
          </p>
        </div>
      </main>
    </div>
  )
}
